//--------------------------------------------------------------------------------------------------
//Requests Pets


//Requests Find
GET http://127.0.0.1:4000/mascotas/buscar HTTP/1.1

//Requests FindId
###
GET http://127.0.0.1:4000/mascotas/buscarid/1 HTTP/1.1

//Requests Create
###
POST http://127.0.0.1:4000/mascotas/crear HTTP/1.1
Content-Type: application/json

{
    "name": "Bongo",
    "species": "Perro",
    "breed": "Mestizo",
    "age": 7,
    "gender": "Macho",
    "size": "Grande",
    "description": "Color Blanco"
    
}

//Requests Update
###
PUT http://127.0.0.1:4000/mascotas/actualizar/2 HTTP/1.1
Content-Type: application/json

{
    "name": "Tini",
    "species": "Gato",
    "breed": "Ruso",
    "age": 5,
    "gender": "Hembra",
    "size": "Pequeño",
    "description": "Color Gris"
    
}

//Requests Delete
###
DELETE http://127.0.0.1:4000/mascotas/borrar/1 HTTP/1.1



//--------------------------------------------------------------------------------------------------
//Requests Adopters

//Requests Find
###
GET http://127.0.0.1:4000/adoptantes/buscar HTTP/1.1

//Requests FindId
###
GET http://127.0.0.1:4000/adoptantes/buscarid/1 HTTP/1.1


//Requests Create
###
POST http://127.0.0.1:4000/adoptantes/crear HTTP/1.1
Content-Type: application/json

{
    "first_name": "Cristian",
    "last_name": "Jacome",
    "email": "cristia69@gmail.com",
    "phone": "3176949584",
    "citizenship_card": "1193522723",
    "address": "Carrera 1" ,
    "city": "Ipiales" 
    
}

//Requests Update
###
PUT http://127.0.0.1:4000/adoptantes/actualizar/2 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Fernando",
    "last_name": "Recalde",
    "email": "fernando@gmail.com",
    "phone": "31111111",
    "citizenship_card": "1193522725",
    "address": "Carrera 2" ,
    "city": "Pasto" 
    
}

//Requests Delete
###
DELETE http://127.0.0.1:4000/adoptantes/borrar/2 HTTP/1.1


//--------------------------------------------------------------------------------------------------
//Requests Adoption_requests

//Requests Find
###
GET http://127.0.0.1:4000/solicitudes/buscar HTTP/1.1

//Requests FindId
###
GET http://127.0.0.1:4000/solicitudes/buscarid/1 HTTP/1.1


//Requests Create
###
POST http://127.0.0.1:4000/solicitudes/crear HTTP/1.1
Content-Type: application/json

{
    "pet_id": 3,          
    "adopter_id": 5,      
    "request_date": "2024-09-25T12:00:00Z", 
    "status": "approved",
    "comments": "Ninguno" 
}


//Requests Update
###
PUT http://127.0.0.1:4000/solicitudes/actualizar/1 HTTP/1.1
Content-Type: application/json

{
    "pet_id": 1,          
    "adopter_id": 1, 
    "status": "Approved",
    "comments": "Hola"
 
}

//Requests Delete
###
DELETE http://127.0.0.1:4000/solicitudes/borrar/4 HTTP/1.1