//--------------------------------------------------------------------------------------------------
//Requests Pets

GET http://127.0.0.1:4000/mascotas/buscar HTTP/1.1


###
GET http://127.0.0.1:4000/mascotas/buscarid/1 HTTP/1.1


###
POST http://127.0.0.1:4000/mascotas/crear HTTP/1.1
Content-Type: application/json

{
    "name": "Bongo",
    "species": "Perro",
    "breed": "Mestizo",
    "age": 7,
    "gender": "Macho",
    "size": "Grande",
    "description": "Color Blanco"
    
}

###
PUT http://127.0.0.1:4000/mascotas/actualizar/2 HTTP/1.1
Content-Type: application/json

{
    "name": "Toni",
    "species": "Gato",
    "breed": "Ruso",
    "age": 5,
    "gender": "Hembra",
    "size": "Pequeño",
    "description": "Color Gris"
    
}

###
DELETE http://127.0.0.1:4000/mascotas/borrar/2 HTTP/1.1



//--------------------------------------------------------------------------------------------------
//Requests Adopters


###
GET http://127.0.0.1:4000/adoptantes/buscar HTTP/1.1


###
GET http://127.0.0.1:4000/adoptantes/buscarid/1 HTTP/1.1



###
POST http://127.0.0.1:4000/adoptantes/crear HTTP/1.1
Content-Type: application/json

{
    "first_name": "Cristian",
    "last_name": "Jacome",
    "email": "cristia69@gmail.com",
    "phone": "3176949584",
    "citizenship_card": "1193522723",
    "address": "Carrera 1" ,
    "city": "Ipiales" 
    
}

###
PUT http://127.0.0.1:4000/adoptantes/actualizar/2 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Fernando",
    "last_name": "Recalde",
    "email": "fernando@gmail.com",
    "phone": "31111111",
    "citizenship_card": "1193522725",
    "address": "Carrera 2" ,
    "city": "Pasto" 
    
}

###
DELETE http://127.0.0.1:4000/adoptantes/borrar/2 HTTP/1.1


//--------------------------------------------------------------------------------------------------
//Requests Adoption_requests

###
GET http://127.0.0.1:4000/solicitudes/buscar HTTP/1.1


###
GET http://127.0.0.1:4000/solicitudes/buscarid/1 HTTP/1.1



###
POST http://127.0.0.1:4000/solicitudes/crear HTTP/1.1
Content-Type: application/json

{
    "pet_id": 1,          
    "adopter_id": 7,      
    "request_date": "2024-09-25T12:00:00Z", 
    "status": "Pending"   
}




###
PUT http://127.0.0.1:4000/solicitudes/actualizar/4 HTTP/1.1
Content-Type: application/json

{
 
    
}

###
DELETE http://127.0.0.1:4000/solicitudes/borrar/4 HTTP/1.1